#!/usr/bin/env bash
set -e

echo 'Clean up'
rm -rf ./deploy

./node_modules/.bin/ng build ui-platform

rm -rf src/lib/node_modules

# Adding config file to ui-platform
cp -R ./src/lib/auth/config ./deploy/ui-platform/auth/

# Adding theming file to ui-platform
cp -R ./src/lib/theme ./deploy/ui-platform/
cp ./src/lib/_theming.scss ./deploy/ui-platform/

# Add pre-loader files
mkdir -p ./deploy/ui-platform/utilities/pre-loader && cp -R ./src/lib/utilities/pre-loader ./deploy/ui-platform/utilities

echo 'Build Complete'
