#!/bin/bash

set -o errexit -o nounset

package="ui-platform"
buildDir="deploy/ui-platform"

commitSha=$(git rev-parse --short HEAD)
commitAuthorName=$(git --no-pager show -s --format='%an' HEAD)
commitAuthorEmail=$(git --no-pager show -s --format='%ae' HEAD)
commitMessage=$(git log --oneline -n 1)

repoName="ui-platform-nightly"
repoUrl="https://github.com/Teradata/vantage-ui-platform-nightly.git"
repoDir="deploy/$repoName"

echo "Start up"
rm -rf $repoDir

echo "Cloning $repoUrl into $repoDir"
git clone $repoUrl $repoDir

echo "Cleaning nightly repo and moving release files into it"
rm -rf $repoDir/*
cp -rf $buildDir/* $repoDir
cd $repoDir

# Prepare Git for pushing the artifacts to the repository.

git config user.name "$commitAuthorName"
git config user.email "$commitAuthorEmail"
git config credential.helper "store --file=.git/credentials"

echo "https://${UI_PLATFORM_NIGHTLY_TOKEN}:@github.com" > .git/credentials

if [ -n "$(git status --porcelain)" ]; then
  git add -A
  git commit -m "$commitMessage"
  git tag "$commitSha"
  git push origin master --tags
  echo "Finished publishing nightly build for ${package}"
else
  echo "No changes to commit for ${package}";
fi
